language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: QIkuFYc1qCaRazMwYnZMMwlB4CZVEB90eqRpWPKX/Bt/iCi16Eck3jtmGdq3hZK5vnS79L9ErRvn4u+tyypWS2sOCfUS3wLwLhIve11XGlautgAhS5DPaygDBTi63RN6wgbfg6DZcQT/UoR4LEhoC7SJZJmqlfyrjF/SjDkSdHhpotYAuLbTkThMd5Gey2jAimcgh8S9FAzb1xuMRKL/vLDoy2pwl01bMT284kcC7hCvRgcKWCjNMuRzHaGvDjxVWEHwllod/HcZRs9IDc+p/c9rNAKaVOtpXSiVCOCgaV88DguQ1Hx5VMKNmvqivHWr1caGdLsPHuaA/jZYyyRz2wqLv00+5AMtfpjn8A6Oy5xWSuE8+Bz4YVIAIlr4Pzn8HbDOt9zlQvSSLBnfkB4qHuGEjd5gmxg8ycgcN4vhjx60jcecZ3JX3ScpZMk8m8ueXXHtRr5qYXnRPuX3r6dII/alqvkPGnK83He+4Efw90q9CJ0MbwmS/IwnXn0jWweSETKFGnZvaVd7WpF6IVZ1SFEbBqAHvHj8NHYeuUhShSevT6dF31lluJM/OBe8T8BjWD0XXPGVSt6mPIQ4oW0WJvH5CGFFuBkuYTwF97nOJDbzFSu2keNd7Na8DT3OcAoOOWo6gChBYBd9JLsB79sWP2//P7xISiWXYnfHyIxXj/o=
  app: maze-09-2016
  on:
    repo: slavyanskii/maze-09-2016
