language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: oIoCfAv4FW4Dvr94uDabQ+em0zEh9T+nfuLOkbt6GHWoP5X1uA8Z+P2vfHsE+LSDxGvpYL+XIWeA+XJvXWcUDnTAJFxfpxx354vEHrA8eTCY8uPnl+b8NaLzoaYYrOGRY5raS17VlYf3x20gSfrv6qR4RKqJCTmltg6OjEosKVtV6wIJdsBOANkT8qYbERyd+ILq18sG5kAslbb9BSm+svr6Qc9L2rEsVCnUMg2WUWmnZrnLwdLidWW2UXTXYywEG0BrS5/U3y2gs4k+KThfMn8SkdAX3cOciTSll4BNrZFeHwxfHepSOBRMExilE+0H6xn0owHMacqJiBt8ABI1dodPde653V46mOsRQSuPAh0TwRU5zIwWnSLKjKgBP6PAhOuSWRSupE4zRiUX3yXvfebDCqsUQG/nmG4cB/8c/laNZSoAduls9MeddeUF4qhX3FQruEMv6D9+y10R+Lq9MQjCNrwElhQixzZFlAaO1MY5g5mUjS+bPY2mkjt7pk7874HlRgfV0s/Sr+tdx8PgYstg3VaJF+KBlQD6J5wXpteWX9gPVGBsCTIDpQTylTRsOnroVdRjUoHrvUH+b0hkLJ1bK2oQSEF0zn4c52fJI7BL6yzgGmxwBKnY6s73jEkQgJs+ihSWOJ5gPsGgThdDkfsri9rXmJ24vdrcEZ440Og=
  app: maze-test-dev
  on:
    repo: slavyanskii/maze-09-2016
