language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: T6emkGAVgjw+g9L0IqW+t/TYnmsfnaLGRPpHkf4q4g/fxmpPXFCHOBHpp+XqXB5/3oXaOIwKHWWac+LEH1SWYSCytwQV8H32SLtAqmjCeSGdGE6jN3h82T/bJWeOJC9JQWMgRVUtPRb6hrAidS62krsviK5nMJyPgZoDxAfr1keq+tGEYFp3FbMr703KsjDEXCr/xWb+2SY4r2zgCTS4ePKl0GhVrtYeM6f9gfmmVaUiXKWIjtulmvEMtovydjgulpO+LD0NJSTjMZB4yaBGfopnuGzyva4Sr1jgkg2nBeLnAsFEE6tqMqQtjqRRWlUnM4khpt1ECD15qhj6XdhPOfkkuUpwxKwXWDCJy6F5CO8x6a63LEtqwITfeN7+teynHpYN4JSe3XkstwZkx3uSC52xyt2cabDFO3o/Iu3z1gKKNR2gacuqFO/XmifiKI5z/yB6DX897Yc/SSijlprXBog7+vrCQmB6qaymz2tzKTVmhPZ4st4c+M63ris5Hv9XbA1l8LDuPtLJv+SdOaEsfpcfFuG/H9aSZm7730SHEq7EBDKLt/bnfMOhpnHFPLUZXsi42VJq8BKPCDRgLnyeH5/jCwr5NgsgM9XFSqtQdUjY59MMVLlk4t8rN+dwiqk8UKw5Qfe3tMUTesOxLUERR9j9enmYXoZA71kOtS9feP8=
  app: maze-09-2016
  on:
    repo: slavyanskii/maze-09-2016
