language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: Lgqk0Zj0vSQD8CLzJWxmuJnzlKfZkkM6H9MQADz3m/B1X9FsNJaz5rBimzL/Dv1YVvNImcSVGQxelJGE0BWe5MpXiGpChhkCHs8vlLfZ+BvzKrkyFH3JDU9uN00zEEb7ofOJwOnmi5QMTd2f7KON9vnx5ZZpCI1rnq9Yq/ttrNcpyeD8d2AI63jF5Rmy2nhqTbLV0ee7uRbfQy75UTy1caRD91OAUPQ6ZNRKOpzdW3jVDlSW2f6EoBvqVoEVlmgHkXj+ijaHrUOn6eBmHVR89UO9w45sdqk+ueGhjmYKngfsZ97lc6RmF7RbGNvVYjFB4vlDc2BcPEb6yIoStKkNaWJt8YghmNqbo2TC9Q+juEvVJTFwwM9o5FzVXxxCW8F2i8XKUDpKI7dPEg3Z8g/2Jjqx0HzYgEnUhj+wByCx2sfzJY1N5390tRqfhENqqouHHrSETRFSQtR7Q1xCvVTGE3c1YWpMh5NAVmbebmhwqbkqvQuojLcNsz4HrM1Iq6E1TXpvgnruTyIl3XBU/LJ+23xNj5JqlDJ9Kp1rcpZ5zElEGF2PV6AFP3Pfhn3hZgV1p+jL1hnXslVjBMw3ICGzj7YEMK+jIqjoy46LLWCEXoto1CDTthx3pn7vPCSIgewlrwuLBK9SGy7CEyKHEnaJve/TRz75FOokVjjobekgQd4=
  app: maze-backend
  on:
    repo: slavyanskii/maze-09-2016
