language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: BJylIxcU3GryMrA1NjlEaHgv3sBKerr3xUtQ5G6nkJu8gd3MBL8m2fhpuMcjZ0sZBeCzRxI5meuTfsI1d1ticRin4wUrH0cT+Vuk+b7LmOoNkeCqBzxL0o0ShaqvHddRuYBYR/OM2rvxTJrWI9nVfTTv23OXZRJ7RmNXY2L+80m9GFEjownynaF1AEgys1FhzNXlit0+Gnw2aOB+vmV0YoHDQf4OfOKoQNnE010qEv6T4zXhECREskZoPFJoWKTUZRN+TrR5lHIjy8ZVJqL/aIRedX1vQ3HLa6NrKuBNiLXHCTwM2p8j1NsCRgOe+FF4GfN3W/7Fk7FHN0U1OTghJ7+QFZw+HMHTqnZT+9CYUiriAfsugi/yMGnnKAVhVd0wo/+lrhthhc7aHcvusbJfVjSNTiIxGAvBB0jAGYfBbZgeaW+gwZZf9d3iXqLNIfpEax9YJ9VYQ7sxJ9J++eZBDSBA+TcAlygtufXPr+s/hS+O7Rab5KGzlpvkIiuj6I/oO03NrshM6Gv6itm4Ji1eQYhndcSgu4q4eeONxkLxO/mezWK/KmiNqgoIoaQHw46tYtkEmg9ep0USJjdP8pyR5C+exalIwNTLUzIldKRDK4crx9ptC+ripkzJkxUk4PchZvErG6Vn0EXRpt1ej6J5tCtixCGmZXtlQu+/w65oVl0=
  app: maze-test
  on:
    repo: slavyanskii/maze-09-2016
