language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: aScMXnMveyamogVg8mZo0yPUgdIvOxP8UAeY9hC7etKz/XMxQbBcIeKuwauHDihjVsNiyYJJ7ZsQ6TMN73hxz63uzRCPXhbpOXxxlV4k4rb9ggZpM9cqI69ceJxpdAHPkbcF2DCd24SSQZhUs88/VNElvlCIFm25MpWw7pxhcvXNIwyzQmt3+VTc3WlNtCWzuYSd99usiFtWQbM1AUIGZ2++82LfNKkoZ96jalp3as/Hgo6J9y6NWEiFJmaWo0X4G3oxdAVQyN+m47HJXvTJImGtFeAO4qaxy2J6vGYeda4tZntWDcemOExMVi4eO/21FF7iNHVlJB75npqqE3Ah08Ybj4Dvetwy1+d8RXgc1YSp+eg/rqSRWB/1jDn6xsP9MjQZSd7T4zQLR7OIb5wNtJdPiaJ36T7XFM9LhTNTpEzC8D0J1Yf5C5wQum5L2OpVEgTGOIBN1q1/tSuT5v7V5oscL2jCKKkKuCloSNzbmtZK21AmalGKOQjUW4D3QOv3L9HdiFxT/5QrN0PfZFBbz+05HVJmsa34KF8ri/xcIYjOREYa4HiXvDEjZ+EVcpU3SBpZ1H4Z0+/h9lmAxp59nNwTAcEDMyfGGdYZIlO+LMJGWTwO5TzW8BFDcJvYSHouZm2KitaGwqYPIY6cdHl6q1nQtJMHJqAOm2n+UO5tRFE=
  app: maze-test-back
  on:
    repo: slavyanskii/maze-09-2016
